# Generated by Django 5.2.13 on 2026-04-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_editora_cidade_editora_email_alter_livro_quantidade'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uploader.image'),
        ),
    ]
